# 1. Pastikan assets (CSS, JS, Gambar) tetap bisa diakses secara langsung
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Hapus semua dibawah ini jika sudah launching ----------------------------------------

# 2. Rewrite: Izinkan akses ke "/commingsoon" (tanpa .html)
# Netlify akan mengambil isi file commingsoon.html tapi URL tetap bersih
[[redirects]]
  from = "/comingsoon"
  to = "/comingsoon.html"
  status = 200

# 3. Redirect: Jika ada yang sengaja mengetik "/comingsoon.html", 
# paksa pindah ke URL bersih "/comingsoon"
[[redirects]]
  from = "/comingsoon.html"
  to = "/comingsoon"
  status = 301
  force = true

# 4. Tangkap semua kunjungan (halaman utama atau halaman lain) 
# dan arahkan ke "/comingsoon" agar URL-nya terlihat bagus
[[redirects]]
  from = "/*"
  to = "/comingsoon"
  status = 302
  force = true